import { usd } from '@cashads/shared';

/**
 * Sandbox catalogue. Every advertiser here is fictional and labelled "(sandbox)"
 * in the UI; payouts are realistic for each vertical (see docs/product-spec.md).
 */

export const SANDBOX_NETWORKS = [
  {
    id: 'sandboxnet',
    name: 'SandboxNet',
    adapter: 'sandboxnet',
    kind: 'offerwall',
    status: 'active',
    config: {},
  },
  {
    id: 'sandbox-ads',
    name: 'SandboxAds',
    adapter: 'pangle_ssv',
    kind: 'ads',
    status: 'active',
    config: { ssv: true },
  },
  {
    id: 'pollnet',
    name: 'PulseCheck Polls',
    adapter: 'native',
    kind: 'native',
    status: 'active',
    config: {},
  },
  {
    id: 'learnhub',
    name: 'LearnHub Sponsors',
    adapter: 'native',
    kind: 'native',
    status: 'active',
    config: {},
  },
  {
    id: 'bitlabs',
    name: 'BitLabs (configure to enable)',
    adapter: 'bitlabs',
    kind: 'iframe_wall',
    status: 'paused',
    config: {
      iframeUrlTemplate: 'https://web.bitlabs.ai/?uid={user_id}&token={app_token}',
      docs: 'https://developer.bitlabs.ai/docs/callbacks',
    },
  },
  {
    id: 'md5wall',
    name: 'MD5-style offerwall (configure to enable)',
    adapter: 'md5wall',
    kind: 'offerwall',
    status: 'paused',
    config: {
      clickUrlTemplate:
        'https://wall.example.com/click?offer={network_offer_id}&subId={user_id}&subId2={click_id}',
    },
  },
] as const;

export interface SeedOffer {
  key: string;
  title: string;
  advertiser: string;
  category: 'survey' | 'app' | 'signup' | 'financial' | 'quick';
  description: string;
  steps: string[];
  payout: number;
  minutes: number;
  dataMb: number;
  paySpeed: 'instant' | 'hours' | 'days';
  countries: string[];
  icon: string;
  color: string;
  tags: string[];
  lite: boolean;
  status?: 'active' | 'paused' | 'scam';
  statusReason?: string;
}

const AFRICA = ['NG', 'GH', 'KE', 'ZA'];

export const SEED_OFFERS: SeedOffer[] = [
  {
    key: 'svy-shopping-2026',
    title: 'Shopping habits 2026',
    advertiser: 'PollPoint Research (sandbox)',
    category: 'survey',
    description:
      'Tell a retail research panel how and where you shop. 18 multiple-choice questions, no personal details.',
    steps: ['Answer 18 multiple-choice questions', 'Pass the attention check', 'Submit on the final page'],
    payout: 1.25,
    minutes: 6,
    dataMb: 0.4,
    paySpeed: 'instant',
    countries: [],
    icon: '🛍️',
    color: '#0ea5e9',
    tags: ['survey', 'retail'],
    lite: true,
  },
  {
    key: 'svy-mobile-money',
    title: 'Mobile money & you',
    advertiser: 'Africa Insights Lab (sandbox)',
    category: 'survey',
    description: 'A fintech research study about how you send, save and receive money on your phone.',
    steps: ['Answer 22 questions', 'Rate 3 app concepts', 'Submit'],
    payout: 2.0,
    minutes: 8,
    dataMb: 0.6,
    paySpeed: 'instant',
    countries: AFRICA,
    icon: '📲',
    color: '#10b981',
    tags: ['survey', 'fintech'],
    lite: true,
  },
  {
    key: 'svy-streaming',
    title: 'What do you stream?',
    advertiser: 'MediaPulse (sandbox)',
    category: 'survey',
    description: 'Music, video and podcast habits for a media brand.',
    steps: ['Answer 20 questions', 'Submit'],
    payout: 1.6,
    minutes: 7,
    dataMb: 0.5,
    paySpeed: 'instant',
    countries: [],
    icon: '🎧',
    color: '#8b5cf6',
    tags: ['survey', 'media'],
    lite: true,
  },
  {
    key: 'svy-smb',
    title: 'Small business owners study',
    advertiser: 'BizVoice (sandbox)',
    category: 'survey',
    description: 'For people who run a business or side hustle: tools, payments and challenges.',
    steps: ['Confirm you run a business', 'Answer 30 questions', 'Submit'],
    payout: 4.0,
    minutes: 12,
    dataMb: 0.8,
    paySpeed: 'instant',
    countries: [],
    icon: '🏪',
    color: '#f59e0b',
    tags: ['survey', 'business', 'high-paying'],
    lite: true,
  },
  {
    key: 'svy-food-quick',
    title: 'Quick opinion: food delivery',
    advertiser: 'QuickTake (sandbox)',
    category: 'survey',
    description: 'Five questions about ordering food online.',
    steps: ['Answer 5 questions'],
    payout: 0.5,
    minutes: 2,
    dataMb: 0.1,
    paySpeed: 'instant',
    countries: [],
    icon: '🍔',
    color: '#ef4444',
    tags: ['survey', 'quick'],
    lite: true,
  },
  {
    key: 'svy-ad-concepts',
    title: 'Rate 3 ad concepts',
    advertiser: 'AdLab Creative (sandbox)',
    category: 'survey',
    description: 'Look at three draft adverts and say which one works best.',
    steps: ['View 3 images', 'Rate each one', 'Pick a favourite'],
    payout: 0.8,
    minutes: 3,
    dataMb: 1.2,
    paySpeed: 'instant',
    countries: [],
    icon: '🎨',
    color: '#ec4899',
    tags: ['survey', 'creative'],
    lite: true,
  },
  {
    key: 'svy-fitness',
    title: 'Health & fitness habits',
    advertiser: 'WellnessWatch (sandbox)',
    category: 'survey',
    description: 'Exercise, sleep and nutrition questions for a health brand.',
    steps: ['Answer 24 questions', 'Submit'],
    payout: 1.8,
    minutes: 9,
    dataMb: 0.5,
    paySpeed: 'instant',
    countries: [],
    icon: '🏃',
    color: '#14b8a6',
    tags: ['survey', 'health'],
    lite: true,
  },
  {
    key: 'app-sandboxpay',
    title: 'Try SandboxPay: send your first ₦100',
    advertiser: 'SandboxPay (sandbox)',
    category: 'app',
    description: 'Install the wallet app, verify your phone and make a ₦100 transfer to anyone.',
    steps: ['Install SandboxPay', 'Verify your phone number', 'Send ₦100 to any account'],
    payout: 2.5,
    minutes: 5,
    dataMb: 24,
    paySpeed: 'instant',
    countries: ['NG'],
    icon: '💸',
    color: '#22c55e',
    tags: ['app', 'fintech'],
    lite: false,
  },
  {
    key: 'app-lingo',
    title: 'Lingo Lite: finish lesson 1',
    advertiser: 'Lingo Lite (sandbox)',
    category: 'app',
    description: 'Install the language app and complete the first 5-minute lesson.',
    steps: ['Install Lingo Lite', 'Pick a language', 'Finish lesson 1'],
    payout: 1.5,
    minutes: 6,
    dataMb: 18,
    paySpeed: 'instant',
    countries: [],
    icon: '🗣️',
    color: '#06b6d4',
    tags: ['app', 'education'],
    lite: false,
  },
  {
    key: 'app-budgetbee',
    title: 'BudgetBee: create your first budget',
    advertiser: 'BudgetBee (sandbox)',
    category: 'app',
    description: 'Set up a monthly budget with at least 3 categories.',
    steps: ['Install BudgetBee', 'Create an account', 'Add 3 budget categories'],
    payout: 3.0,
    minutes: 8,
    dataMb: 30,
    paySpeed: 'hours',
    countries: [],
    icon: '🐝',
    color: '#eab308',
    tags: ['app', 'finance'],
    lite: false,
  },
  {
    key: 'app-newsnow',
    title: 'NewsNow: read 3 articles',
    advertiser: 'NewsNow (sandbox)',
    category: 'app',
    description: 'Install the news app and read any three articles.',
    steps: ['Install NewsNow', 'Read 3 articles'],
    payout: 0.7,
    minutes: 4,
    dataMb: 12,
    paySpeed: 'instant',
    countries: [],
    icon: '📰',
    color: '#64748b',
    tags: ['app', 'news'],
    lite: false,
  },
  {
    key: 'sgn-jobbridge',
    title: 'Create a free JobBridge profile',
    advertiser: 'JobBridge (sandbox)',
    category: 'signup',
    description: 'Sign up to a job-matching site and complete your profile basics.',
    steps: ['Sign up with your email', 'Add your skills', 'Confirm your email'],
    payout: 1.2,
    minutes: 4,
    dataMb: 1.5,
    paySpeed: 'instant',
    countries: [],
    icon: '💼',
    color: '#3b82f6',
    tags: ['signup', 'jobs'],
    lite: true,
  },
  {
    key: 'sgn-greenbox',
    title: 'Join the GreenBox newsletter',
    advertiser: 'GreenBox Meals (sandbox)',
    category: 'signup',
    description: 'Double opt-in to a recipes newsletter. Unsubscribe any time.',
    steps: ['Enter your email', 'Confirm the subscription'],
    payout: 0.4,
    minutes: 1,
    dataMb: 0.2,
    paySpeed: 'instant',
    countries: [],
    icon: '🥗',
    color: '#84cc16',
    tags: ['signup', 'quick'],
    lite: true,
  },
  {
    key: 'sgn-clouddrive',
    title: 'Open a free CloudNest account',
    advertiser: 'CloudNest (sandbox)',
    category: 'signup',
    description: 'Create a free cloud-storage account and upload one file.',
    steps: ['Sign up', 'Upload any file'],
    payout: 1.0,
    minutes: 3,
    dataMb: 3,
    paySpeed: 'instant',
    countries: [],
    icon: '☁️',
    color: '#0284c7',
    tags: ['signup', 'productivity'],
    lite: true,
  },
  {
    key: 'fin-sandboxbank',
    title: 'Open & fund a SandboxBank savings account',
    advertiser: 'SandboxBank (sandbox)',
    category: 'financial',
    description:
      'Open a high-yield savings account and deposit $10 (it stays yours). FDIC-style protection in the sandbox story.',
    steps: ['Apply online (5 min)', 'Verify your identity', 'Deposit $10 within 7 days'],
    payout: 120,
    minutes: 15,
    dataMb: 4,
    paySpeed: 'days',
    countries: ['US'],
    icon: '🏦',
    color: '#1d4ed8',
    tags: ['financial', 'high-paying'],
    lite: true,
  },
  {
    key: 'fin-naijaneo',
    title: 'NaijaNeo Bank: open an account + first transfer',
    advertiser: 'NaijaNeo Bank (sandbox)',
    category: 'financial',
    description: 'Open a free digital bank account with your BVN and make one transfer of any amount.',
    steps: ['Download NaijaNeo', 'Verify with BVN', 'Make one transfer'],
    payout: 8.0,
    minutes: 12,
    dataMb: 35,
    paySpeed: 'hours',
    countries: ['NG'],
    icon: '🟢',
    color: '#16a34a',
    tags: ['financial', 'high-paying'],
    lite: false,
  },
  {
    key: 'fin-coverquick',
    title: 'Get a car insurance quote',
    advertiser: 'CoverQuick (sandbox)',
    category: 'financial',
    description: 'Compare quotes in 6 minutes. No purchase needed.',
    steps: ['Enter vehicle details', 'Review 3 quotes'],
    payout: 18,
    minutes: 6,
    dataMb: 2,
    paySpeed: 'hours',
    countries: ['US', 'GB', 'CA'],
    icon: '🚗',
    color: '#0f766e',
    tags: ['financial', 'insurance'],
    lite: true,
  },
  {
    key: 'fin-stackup',
    title: 'Invest your first $5 with StackUp',
    advertiser: 'StackUp Invest (sandbox)',
    category: 'financial',
    description: 'Open an investing account and buy $5 of any fund.',
    steps: ['Open account', 'Verify identity', 'Invest $5'],
    payout: 40,
    minutes: 10,
    dataMb: 5,
    paySpeed: 'days',
    countries: ['US', 'GB', 'AU'],
    icon: '📈',
    color: '#4f46e5',
    tags: ['financial', 'investing'],
    lite: true,
  },
  {
    key: 'fin-coinnest',
    title: 'CoinNest: verify your exchange account',
    advertiser: 'CoinNest (sandbox)',
    category: 'financial',
    description: 'Create and verify an account on a licensed exchange. No deposit required.',
    steps: ['Sign up', 'Complete identity verification'],
    payout: 15,
    minutes: 12,
    dataMb: 6,
    paySpeed: 'days',
    countries: ['NG', 'GH', 'KE', 'ZA', 'IN', 'PH', 'BR', 'GB', 'DE', 'AU', 'CA'],
    icon: '🪺',
    color: '#d97706',
    tags: ['financial', 'crypto'],
    lite: true,
  },
  {
    key: 'fin-pesasafe',
    title: 'PesaSafe: first savings deposit',
    advertiser: 'PesaSafe (sandbox)',
    category: 'financial',
    description: 'Open a mobile savings pot and deposit KSh 100.',
    steps: ['Install PesaSafe', 'Deposit KSh 100'],
    payout: 5,
    minutes: 8,
    dataMb: 15,
    paySpeed: 'hours',
    countries: ['KE'],
    icon: '🐖',
    color: '#be185d',
    tags: ['financial', 'savings'],
    lite: false,
  },
  {
    key: 'svy-uk-commute',
    title: 'UK commuter survey',
    advertiser: 'TransitTalk (sandbox)',
    category: 'survey',
    description: 'How you get to work and what would improve it.',
    steps: ['Answer 20 questions'],
    payout: 2.2,
    minutes: 8,
    dataMb: 0.4,
    paySpeed: 'instant',
    countries: ['GB'],
    icon: '🚆',
    color: '#9333ea',
    tags: ['survey'],
    lite: true,
  },
  {
    key: 'svy-in-phones',
    title: 'Smartphone usage in India',
    advertiser: 'Bharat Pulse (sandbox)',
    category: 'survey',
    description: 'Apps, data packs and payments on your phone.',
    steps: ['Answer 18 questions'],
    payout: 1.1,
    minutes: 6,
    dataMb: 0.4,
    paySpeed: 'instant',
    countries: ['IN'],
    icon: '📱',
    color: '#f97316',
    tags: ['survey'],
    lite: true,
  },
  {
    key: 'app-pisopay',
    title: 'PisoPay: first top-up',
    advertiser: 'PisoPay (sandbox)',
    category: 'app',
    description: 'Install the e-wallet and top up ₱50.',
    steps: ['Install PisoPay', 'Top up ₱50'],
    payout: 3.5,
    minutes: 7,
    dataMb: 20,
    paySpeed: 'instant',
    countries: ['PH'],
    icon: '💙',
    color: '#2563eb',
    tags: ['app', 'fintech'],
    lite: false,
  },
  {
    key: 'sgn-volta',
    title: 'Volta cashback: link Pix',
    advertiser: 'Volta (sandbox)',
    category: 'signup',
    description: 'Create a cashback account and link a Pix key.',
    steps: ['Sign up', 'Link your Pix key'],
    payout: 2.8,
    minutes: 5,
    dataMb: 2,
    paySpeed: 'instant',
    countries: ['BR'],
    icon: '⚡',
    color: '#facc15',
    tags: ['signup', 'cashback'],
    lite: true,
  },
  {
    key: 'svy-gh-fintech',
    title: 'Ghana fintech pulse',
    advertiser: 'Accra Analytics (sandbox)',
    category: 'survey',
    description: 'MoMo, banks and savings — 15 questions.',
    steps: ['Answer 15 questions'],
    payout: 1.7,
    minutes: 6,
    dataMb: 0.3,
    paySpeed: 'instant',
    countries: ['GH'],
    icon: '🇬🇭',
    color: '#dc2626',
    tags: ['survey', 'fintech'],
    lite: true,
  },
  {
    key: 'qk-logo-pick',
    title: 'Tap test: pick your favourite logo',
    advertiser: 'BrandSpark (sandbox)',
    category: 'quick',
    description: 'One question: which of four logos do you like most?',
    steps: ['Pick one logo'],
    payout: 0.25,
    minutes: 0.75,
    dataMb: 0.3,
    paySpeed: 'instant',
    countries: [],
    icon: '👆',
    color: '#a855f7',
    tags: ['quick'],
    lite: true,
  },
  {
    key: 'qk-store-hours',
    title: 'Verify a store’s opening hours',
    advertiser: 'MapFix (sandbox)',
    category: 'quick',
    description: 'Confirm whether a listed shop near you is open — helps fix map data.',
    steps: ['Check the listing', 'Answer yes/no'],
    payout: 0.35,
    minutes: 1.5,
    dataMb: 0.5,
    paySpeed: 'instant',
    countries: [],
    icon: '🗺️',
    color: '#0891b2',
    tags: ['quick', 'local'],
    lite: true,
  },
  {
    key: 'scam-vip-unlock',
    title: 'Earn $50 in 2 minutes — VIP unlock',
    advertiser: 'QuickRichVIP',
    category: 'signup',
    description: 'Promised $50 for a “VIP unlock” that required an upfront fee.',
    steps: ['Pay the unlock fee'],
    payout: 2,
    minutes: 2,
    dataMb: 1,
    paySpeed: 'instant',
    countries: [],
    icon: '🚩',
    color: '#991b1b',
    tags: ['removed'],
    lite: true,
    status: 'scam',
    statusReason: 'Required an upfront “unlock fee” — confirmed by 7 member reports',
  },
  {
    key: 'spam-dealz',
    title: 'SpamDealz: enter to win',
    advertiser: 'SpamDealz',
    category: 'signup',
    description: 'Prize draw sign-up.',
    steps: ['Enter details'],
    payout: 0.6,
    minutes: 2,
    dataMb: 1,
    paySpeed: 'instant',
    countries: [],
    icon: '🎰',
    color: '#7f1d1d',
    tags: ['paused'],
    lite: true,
    status: 'paused',
    statusReason: 'Auto-paused after multiple member reports — under review',
  },
];

export const SEED_CREATIVES = [
  {
    id: 'ad-sunfresh',
    advertiser: 'SunFresh Juice',
    title: 'Squeezed this morning',
    tagline: 'No sugar added. Ever.',
    durationSeconds: 15,
    revenue: 0.01,
    lite: true,
    theme: { from: '#f97316', to: '#facc15', accent: '#fff7ed', emoji: '🍊' },
  },
  {
    id: 'ad-voltbike',
    advertiser: 'Volt e-bikes',
    title: 'Beat the traffic',
    tagline: 'Pay weekly. Ride daily.',
    durationSeconds: 20,
    revenue: 0.014,
    lite: true,
    theme: { from: '#0f172a', to: '#22d3ee', accent: '#ecfeff', emoji: '🚲' },
  },
  {
    id: 'ad-learnly',
    advertiser: 'Learnly',
    title: 'Learn to code in 12 weeks',
    tagline: 'Pay when you get hired.',
    durationSeconds: 25,
    revenue: 0.018,
    lite: true,
    theme: { from: '#4f46e5', to: '#a855f7', accent: '#eef2ff', emoji: '💻' },
  },
  {
    id: 'ad-naijaneo',
    advertiser: 'NaijaNeo Bank',
    title: 'Free transfers, forever',
    tagline: 'Open an account in 3 minutes.',
    durationSeconds: 30,
    revenue: 0.022,
    lite: false,
    theme: { from: '#065f46', to: '#34d399', accent: '#ecfdf5', emoji: '🟢' },
  },
  {
    id: 'ad-greenbox',
    advertiser: 'GreenBox Meals',
    title: 'Dinner, sorted',
    tagline: 'Fresh ingredients, 20-minute recipes.',
    durationSeconds: 20,
    revenue: 0.012,
    lite: true,
    theme: { from: '#3f6212', to: '#a3e635', accent: '#f7fee7', emoji: '🥗' },
  },
  {
    id: 'ad-cloudnest',
    advertiser: 'CloudNest',
    title: 'Your photos, safe',
    tagline: '15 GB free. No ads.',
    durationSeconds: 15,
    revenue: 0.009,
    lite: true,
    theme: { from: '#0369a1', to: '#7dd3fc', accent: '#f0f9ff', emoji: '☁️' },
  },
];

export const SEED_CHARITIES = [
  {
    id: 'lagos-food',
    name: 'Lagos Food Bank (sandbox)',
    description: 'Rescues surplus food and delivers meals to families in Lagos.',
    icon: '🍲',
    url: 'https://example.org/lagos-food',
    impactUnit: 'meal',
    impact: 0.5,
  },
  {
    id: 'clean-water',
    name: 'Clean Water Fund (sandbox)',
    description: 'Builds and repairs community boreholes.',
    icon: '💧',
    url: 'https://example.org/clean-water',
    impactUnit: 'day of clean water',
    impact: 0.25,
  },
  {
    id: 'code-girls',
    name: 'Girls Code Africa (sandbox)',
    description: 'Free coding classes for girls aged 12–18.',
    icon: '👩🏾‍💻',
    url: 'https://example.org/code-girls',
    impactUnit: 'hour of coding class',
    impact: 1,
  },
  {
    id: 'plant-trees',
    name: 'Plant a Tree Africa (sandbox)',
    description: 'Reforestation with local farmers.',
    icon: '🌳',
    url: 'https://example.org/trees',
    impactUnit: 'tree planted',
    impact: 0.3,
  },
];

export const toMicros = usd;
